### ISSUE TITLE
FairyGUI-haxe  Warning

### ISSUE THREAD

**Issue by match08** [rakuten/FairyGUI-haxe#1]
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenx909/rule/ArrayRuleX.hx:67: characters 5-12 : Warning : private structure fields are deprecated
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenxcore/Tools.hx:70: characters 26-32 : Duplicate access modifier inline
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenxcore/Tools.hx:70: characters 19-25 : Previously defined here
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenxcore/Tools.hx:74: characters 26-32 : Duplicate access modifier inline
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenxcore/Tools.hx:74: characters 19-25 : Previously defined here
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenxcore/Tools.hx:78: characters 26-32 : Duplicate access modifier inline
D:/HaxeToolkit/haxe/lib/fairygui/git/src/tweenxcore/Tools.hx:78: characters 19-25 : Previously defined here
D:/HaxeToolkit/haxe/lib/fairygui/git/src/FastXML.hx:83: characters 41-61 : In haxe 4, implements Dynamic is only supported on externs
D:/HaxeToolkit/haxe/lib/fairygui/git/src/FastXML.hx:66: characters 40-53 : In haxe 4, implements Dynamic is only supported on externs
D:/HaxeToolkit/haxe/lib/fairygui/git/src/FastXML.hx:47: characters 42-55 : In haxe 4, implements Dynamic is only supported on externs
D:/HaxeToolkit/haxe/lib/fairygui/git/src/FastXML.hx:25: characters 39-54 : In haxe 4, implements Dynamic is only supported on externs
D:/HaxeToolkit/haxe/lib/fairygui/git/src/FastXML.hx:2: characters 37-53 : In haxe 4, implements Dynamic is only supported on externs

**Comment by rakuten** [comment]
不知道你用的是什么版本的haxe库，用3.4.7的应该是没问题的，4.0的兼容工作一直没处理过，谁让它正式版也一直没发布....:p

有问题你可以直接在fgui的官方QQ群里@我

**Comment by match08** [comment]
haxe4 正式版本发布了

**Comment by rakuten** [comment]
很抱歉，但我现在改写C#去了....
